### ISSUE TITLE
Native Apple Silicon Build

### ISSUE THREAD

**Issue by ipfans** [system-sdk/system-designer-electron#3]
System Designer released Intel build and works fine with Apple Silicon currently, but it will some performance issue run under Rosetta 2. So it will be great to have arm64 build.

**Comment by ecarriou** [comment]
Thanks for your suggestion! In fact I have planned to add build for arm very soon (just need the time to do that).

**Comment by ecarriou** [comment]
It has been done in v4.7.0. 
Tested with my MacBook Air m1, performance is really improved.

**Comment by ecarriou** [comment]
For information, System Designer v4.7.0 (with M1 silicon chips compatibility)is now on Mac App Store. Enjoy!
